from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

MISSING_FEATURE_CODES = {"UNKNOWN_COMMAND", "NOT_IMPLEMENTED"}


def _get_path(obj, dotted: str):
    cur = obj
    for part in dotted.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        elif isinstance(cur, list) and part.isdigit():
            idx = int(part)
            if 0 <= idx < len(cur):
                cur = cur[idx]
            else:
                return None
        else:
            return None
    return cur


def _eval_assertion(state: dict, a: dict) -> tuple[bool, str]:
    target = _get_path(state, a["path"])
    kind = a["kind"]
    value = a.get("value")
    if kind == "exists":
        ok = target is not None and (not isinstance(target, list) or len(target) > 0)
        return ok, f"path {a['path']} exists={'true' if ok else 'false'}"
    if kind == "count":
        n = len(target) if isinstance(target, (list, dict)) else (1 if target is not None else 0)
        ok = n == value
        return ok, f"{a['path']} count={n} expected={value}"
    if kind == "equals":
        return target == value, f"{a['path']}={target!r} expected={value!r}"
    if kind == "approx":
        tol = a.get("tolerance", 0)
        ok = isinstance(target, (int, float)) and abs(target - value) <= tol
        return ok, f"{a['path']}={target} ~ {value} (tol {tol})"
    return False, f"unknown assertion kind {kind}"


def run(qa_dir: Path, qa_results: dict) -> None:
    issues: list[dict] = []
    missing: list[dict] = []

    for sc in qa_results["scenarios"]:
        artifacts = Path(sc["artifactsDir"])
        # classify command/capture errors
        for e in sc["errors"]:
            code = e.get("code", "INTERNAL")
            step = e.get("step", "?")
            cmd = e.get("command") or (f"capture:{e.get('artifact')}" if e.get("artifact") else "?")
            rec = {
                "scenario": sc["scenario"], "step": step, "command": cmd,
                "code": code, "error": e.get("error", ""),
            }
            if code in MISSING_FEATURE_CODES:
                missing.append(rec)
            else:
                issues.append({**rec, "type": "error"})
        # evaluate assertions against captured state
        for yf in sorted((qa_dir / "scenarios").glob("*.yaml")):
            if yf.name != sc["scenario"]:
                continue
            scenario = __import__("eq.dsl.loader", fromlist=["load_scenario"]).load_scenario(yf)
            state_files = {p.name: p for p in (artifacts / "states" / "homely").glob("step-*.json")}
            for a in scenario.assertions:
                sf = f"step-{a.at}.json"
                if sf not in state_files:
                    issues.append({
                        "scenario": sc["scenario"], "step": a.at, "command": a.artifact,
                        "code": "NO_ARTIFACT", "error": f"missing {sf} for assertion",
                        "type": "assertion", "detail": f"{a.kind} {a.path} = {a.get('value')}",
                    })
                    continue
                state = json.loads(state_files[sf].read_text())
                ok, detail = _eval_assertion(state, a.model_dump())
                if not ok:
                    issues.append({
                        "scenario": sc["scenario"], "step": a.at, "command": a.artifact,
                        "code": "ASSERTION_FAILED", "error": detail,
                        "type": "assertion", "detail": f"{a.kind} {a.path}",
                    })

    _write_issues(qa_dir, issues)
    _write_missing(qa_dir, missing)
    print(f"[qa] {len(issues)} bug(s), {len(missing)} missing feature(s)")
    return None


def _write_issues(qa_dir: Path, issues: list[dict]) -> None:
    lines = ["# QA Issues (bugs)", "", "_Generated by qa-loop. Do not hand-edit; re-run to refresh._", ""]
    if not issues:
        lines.append("No bugs detected. ✅")
    else:
        for i, it in enumerate(issues, 1):
            lines.append(f"## {i}. [{it['type']}] {it['command']} (step {it['step']})")
            lines.append(f"- scenario: `{it['scenario']}`")
            lines.append(f"- code: `{it['code']}`")
            lines.append(f"- detail: {it.get('detail', it.get('error', ''))}")
            lines.append(f"- raw: {it.get('error', '')}")
            lines.append("")
    (qa_dir / "ISSUES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_missing(qa_dir: Path, missing: list[dict]) -> None:
    lines = ["# Missing Features", "", "_Generated by qa-loop from UNKNOWN_COMMAND/NOT_IMPLEMENTED responses + documented gaps. Re-run to refresh._", ""]
    seed = [
        ".sh3d save/open round-trip (save/open commands persist Homely's own JSON format via home-persistence.ts, not SH3D's binary .sh3d format — by design, see docs; cross-format import/export unverified)",
        "Door/window wall opening is a visual-attachment simplification, not a true geometric cutout (M5): the piece attaches to the wall and renders on top of it; the wall body itself is not yet subtracted/notched in plan or 3D.",
    ]
    lines.append("## Confirmed by run")
    if missing:
        for m in missing:
            lines.append(f"- `{m['command']}` → {m['code']}: {m['error']} (scenario {m['scenario']})")
    else:
        lines.append("- none this run")
    lines.append("")
    lines.append("## Documented / suspected (verify in next runs)")
    for s in seed:
        lines.append(f"- {s}")
    (qa_dir / "MISSING_FEATURES.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
